name: ${project.name}
description: ${project.description}
version: ${project.version}
main: ${main.class}
author: ${author}
api-version: 1.13
depend: [LuckPerms]
softdepend: [PlaceholderAPI]
commands:
  lpc:
    description: LPC commands.
    usage: "Usage: /lpc <reload|clear|debug>"
permissions:
  lpc.reload:
    description: Allows use of /lpc reload
    default: op
  lpc.clearchat:
    description: Allows use of /lpc clear
    default: op
  lpc.debug:
    description: Allows use of /lpc debug
    default: op
  lpc.colorcodes:
    description: Allows color codes in chat messages
    default: false
  lpc.rgbcodes:
    description: Allows RGB/hex color codes in chat messages
    default: false
