name: EzChat
version: 1.0.0
main: com.ezinnovations.ezchat.EzChat
author: ezinnovations
description: Lightweight chat formatter with chat toggle support
api-version: 1.21
folia-supported: true
depend: [LuckPerms]
softdepend: [PlaceholderAPI, floodgate, Geyser-Spigot]
commands:
  lpc:
    description: EzChat commands.
    usage: "Usage: /lpc <reload|clear|debug>"
  chattoggle:
    description: Toggle receiving public chat.
    usage: "Usage: /chattoggle"
permissions:
  lpc.reload:
    description: Allows use of /lpc reload
    default: op
  lpc.clearchat:
    description: Allows use of /lpc clear
    default: op
  lpc.debug:
    description: Allows use of /lpc debug
    default: op
  lpc.colorcodes:
    description: Allows color codes in chat messages
    default: false
  lpc.rgbcodes:
    description: Allows RGB/hex color codes in chat messages
    default: false
  lpc.chattoggle:
    description: Allows use of /chattoggle
    default: true
